# Generated by Django 4.2.3 on 2023-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
